//mymainF429v02.c wmh 2019-02-17 : uses SysTick_msecs generated by SysTick_Handler to time blinking
//mymainF429v01.c wmh 2018-08-13a : 'Blinky' adaptation for STM32F429I-DISC1 board

// Includes ------------------------------------------------------------------
#include <stdint.h>	//for uint8_t, uint16_t, uint32_t  etc. 
#include "myIncludes03.h"	//hardware register addresses

#define BUFF_SIZE 20

//miscellaneous functions used here -- see .S files for definitions
void initPG13();	// in '05Blinky_LD3.S'
void togglePG13();	// ""
void setPG13();		// ""
void resetPG13();	// ""
void initSysTick();	// in 'mySysTick_Handler.S'

//functions defined in library libUSART1_AC6gcc_nodebug.a
void initUSART1(void);			//must call before using any functions below
int32_t nbUSART1_getchar(void); //non-blocking; returns received char >= 0 or -1 if fail/no char
int32_t nbUSART1_putchar(char);	//non-blocking; returns +1 if char sent, -1 if fail to send
int32_t bUSART1_getchar(void);	//blocking; does not return until character is received
void bUSART1_putchar(char);		//blocking; does not return until character is sent
void USART1_writeDR(char);		//debug: unconditional write to USART1 DR

void buffer_handler(char);
void write_handler();

uint16_t SysTick_msecs = 0; 	//defined here but updated in 'mySysTick_Handler.S'
uint32_t SysTick_secs = 0;		// ""	
char buffer[BUFF_SIZE + 3];


int main(void) // does some data access demos then blinks the green LED forever 
{
	
	int a;
	int i;
	int c;
	initPG13(); 	//initialize the PG13 port pin which drives the green LED (LD3)
	initSysTick();	//turn on the msec timer
	initUSART1();	//initialize USART1 to talk at 9600N81 (relayed through ST-LINK)
	//USART1_IRQinit();
	i = 2;


	while (1) //echo characters received on serial port while blinking
	{

		write_handler();
		a = nbUSART1_getchar();
		if(a <=126 && a>=32){
			buffer_handler(a);
		}
		if(a==0xd){
			buffer[2] = 1;
		}

	}



}

