//mymainF429v02.c wmh 2019-02-17 : uses SysTick_msecs generated by SysTick_Handler to time blinking
//mymainF429v01.c wmh 2018-08-13a : 'Blinky' adaptation for STM32F429I-DISC1 board

// Includes ------------------------------------------------------------------
#include <stdint.h>	//for uint8_t, uint16_t, uint32_t  etc. 
#include "myIncludes03.h"	//hardware register addresses



//miscellaneous functions used here -- see .S files for definitions
void initPG13();	// in '05Blinky_LD3.S'
void togglePG13();	// ""
void setPG13();		// ""
void resetPG13();	// ""
void initSysTick();	// in 'mySysTick_Handler.S'

//functions defined in library libUSART1_AC6gcc_nodebug.a
void initUSART1(void);			//must call before using any functions below
int32_t nbUSART1_getchar(void); //non-blocking; returns received char >= 0 or -1 if fail/no char
int32_t nbUSART1_putchar(char);	//non-blocking; returns +1 if char sent, -1 if fail to send
int32_t bUSART1_getchar(void);	//blocking; does not return until character is received
void bUSART1_putchar(char);		//blocking; does not return until character is sent
void USART1_writeDR(char);		//debug: unconditional write to USART1 DR


uint16_t SysTick_msecs = 0; 	//defined here but updated in 'mySysTick_Handler.S'
uint32_t SysTick_secs = 0;		// ""	


uint32_t loadCONSTANT_00(void);	//demo function in myDataOps.S
uint32_t loadVARIABLE_00(void);	// ""
void storeVARIABLE_00(void);	// ""
uint32_t loadDword(void);		// ""
extern uint32_t Dword;			// variable defined in myDataOps.S

//int IT_ascii2num(int c);
//int TBB_ascii2num(int c);

int main(void) // does some data access demos then blinks the green LED forever 
{
	//data operations done in the C environment -- view in debugger disassembly to understand what is done
	int32_t x=0x89ABCDEE;
	x=Dword;
	//char c [10] = {'1', '0','A','9','/','f','5'};
	//int r [10];
	//int rtbb [10];

	//int i = 0;
	//int j = 10;
	//int count = 0;
	//int total;
	//int total2;


	//for(i = 0; i < 7; i++){
	//	r[i] = IT_ascii2num(c[i]);
	//	rtbb[i] = TBB_ascii2num(c[i]);
	//}

	//data operations done by functions in assembler -- see how they operate
	//x=loadDword();
	//x= loadCONSTANT_00();
	//x= loadVARIABLE_00();
	//storeVARIABLE_00();
	//x= loadVARIABLE_00();
	
	initPG13(); 	//initialize the PG13 port pin which drives the green LED (LD3)
	initSysTick();	//turn on the msec timer
	initUSART1();	//initialize USART1 to talk at 9600N81 (relayed through ST-LINK)
	USART1_IRQinit();

	while (1) //echo characters received on serial port while blinking
	{

		if( SysTick_msecs <5 ) { //short 'on'
			setPG13();
		}
		if( SysTick_msecs >=5 ) { //long 'off'
			resetPG13();
		}

		//nbUSART1_putchar('a');	// echo a different character value back to sender

	}



}

